version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    user: '1000:1000'
    container_name: 11ty_dev
    command: sh wrapper_script.sh
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - nodemodules:/app/node_modules

volumes:
  nodemodules: {}
