services:
  app:
    command:
      - /bin/sh
      - -c
      - |
        npm run watch &
        npm run serve &
        wait -n # Wait for any process to exit
        exit $? # Exit with status of process that exited first
    volumes:
      - ".:/app"
